site_name: 2021.1 - PC-GO

repo_name: "2021.1-PC-GO"
repo_url: "https://github.com/fga-eps-mds/2021.1-PC-GO"

theme:
  name: "material"
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: pt

nav:
  - Home: index.html
  - Documentação:
      - Equipe: equipe.md
      - Documento de Arquitetura: documento-de-arquitetura.md
      - Metodologia: metodologia.md
      - Informações dos Membros: info-dos-membros.md
      - Identidade Visual: identidade-visual.md
      - Backlog do Produto: backlog.md
      - Documento de Visão: documento-de-visao.md
      - Roadmap: roadmap.md
      - Protótipo de Alta Fidelidade: prototipo.md
      - Protótipo de Baixa Fidelidade: prototipo-baixa-fidelidade.md
      - Apresentações: apresentacoes.md

  - Lean Inception:
      - Introdução: leanInception/introducao-lean-inception.md
      - Visão de Produto: leanInception/visao-do-produto.md
      - é - não é - faz - não faz: leanInception/e-naoe-faz-naofaz.md
      - Objetivo do Produto: leanInception/objetivo-do-negocio.md
      - Personas: leanInception/persona.md
      - Jornada do Usuário: leanInception/jornada-de-usuario.md
      - Brainstormig de Funcionalidades: leanInception/brainstorming-de-funcionalidades.md
      - Revisão Técnica, de Negócio e de UX: leanInception/revisao-tecnica.md
      - Sequenciador: leanInception/sequenciador.md
      - Canvas MVP: leanInception/canvasmvp.md

  - Comunidade:
      - Guia de Contribuição: CONTRIBUTING.md
      - Código de Conduta: codigo-de-conduta.md

  - Sprints:
      - Sprint 0:
          - Planning: sprints/sprint0/planning.md
          - Review: sprints/sprint0/review.md
          - Retrospectiva: sprints/sprint0/retro.md

      - Sprint 1:
          - Planning: sprints/sprint1/planning.md
          - Review: sprints/sprint1/review.md
          - Retrospectiva: sprints/sprint1/retro.md

      - Sprint 2:
          - Planning: sprints/sprint1/planning.md
